# Generated by Django 5.2.6 on 2025-09-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_buyer_profile_alter_farmer_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
