# Generated by Django 5.2.6 on 2025-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer')], default='BUYER', max_length=10),
        ),
    ]
